[project]
name = "pythonic-function-calling-data"
version = "0.1.0"
description = "Repository for the Pythonic Function Calling data generation with Dria Network"
authors = [
  { name = "andthattoo" }
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "httpx==0.28.1",
  "openai>=1.44.0",
  "jsonschema>=4.23.0",
  "matplotlib>=3.7.0",
  "numpy>=1.26,<2",
  "transformers>=4.37.0",
  "python-dateutil>=2.8.2",
]
